sanatorium/sanatorium/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import main

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('users.urls', namespace='accounts'), name='accounts'),
    path('users/', include('users.urls', namespace='users'), name='users'),
    path('therapy/', include('therapy.urls', namespace='therapy'), name='therapy'),
    path('cooperation/', include('cooperation.urls', namespace='cooperation'), name='cooperation'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),

    path('', login_required(main), name=''),
    path('main/', login_required(main), name='main')
]

sanatorium/therapy/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import DiseaseDelete, DiseaseList, DiseaseUpdate, DiseaseCreate, \
                    SymptomDelete, SymptomList, SymptomUpdate, SymptomCreate

app_name = 'therapy'

urlpatterns = [
  path('disease_list/', login_required(DiseaseList.as_view()), name='disease_list'),
  path('disease_create/', login_required(DiseaseCreate.as_view()), name='disease_create'),
  path('disease/<int:pk>/', login_required(DiseaseUpdate.as_view()), name='disease_update'),
  path('disease_delete/<int:pk>/', login_required(DiseaseDelete.as_view()), name='disease_delete'),

  path('symtom_list/', login_required(SymptomList.as_view()), name='symptom_list'),
  path('symtom_create/', login_required(SymptomCreate.as_view()), name='symptom_create'),
  path('symtom/<int:pk>/', login_required(SymptomUpdate.as_view()), name='symptom_update'),
  path('symtom_delete/<int:pk>/', login_required(SymptomDelete.as_view()), name='symptom_delete')
]

sanatorium/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import myprofile, signup, myprofile_edit, profile, \
                    EmployeeList, EmployeeCreate, EmployeeUpdate, EmployeeDelete, \
                    PatientList, PatientCreate, PatientUpdate, PatientDelete, \
                    UserList, UserUpdate

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='/main'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/users/login'), name='logout'),
    path('myprofile/',  login_required(myprofile), name='myprofile'),
    path('profile/<int:pk>',  login_required(profile), name='profile'),
    path('myprofile_edit', login_required(myprofile_edit), name='myprofile_edit'),
    path('signup/', signup, name='signup'),

    path('employee_list/', login_required(EmployeeList.as_view()), name='employee_list'),
    path('employee_create/', login_required(EmployeeCreate.as_view()), name='employee_create'),
    path('employee/<int:pk>/', login_required(EmployeeUpdate.as_view()), name='employee_update'),
    path('employee_delete/<int:pk>/', login_required(EmployeeDelete.as_view()), name='employee_delete'),
    
    path('patient_list/', login_required(PatientList.as_view()), name='patient_list'),
    path('patient_create/', login_required(PatientCreate.as_view()), name='patient_create'),
    path('patient/<int:pk>/', login_required(PatientUpdate.as_view()), name='patient_update'),
    path('patient_delete/<int:pk>/', login_required(PatientDelete.as_view()), name='patient_delete'),

    path('user_list/', login_required(UserList.as_view()), name='user_list'),
    path('user/<int:pk>/', login_required(UserUpdate.as_view()), name='user_update'),
]

sanatorium/therapy/models.py
from django.db import models

class Disease(models.Model):
  name = models.CharField(max_length=254)
  description_ref = models.CharField(max_length=500, null=True, blank=True)
  
  def __str__(self):
    return f"{self.name}"


class Symptom(models.Model):
  name = models.CharField(max_length=254)
  description_ref = models.CharField(max_length=500, null=True, blank=True)
  
  def __str__(self):
    return f"{self.name}"

sanatorium/therapy/views.py
import imp
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from multiprocessing import context, get_context
from django.shortcuts import render, redirect
from .models import Disease, Symptom
from meclasses.MeAccessManager import MeAccessManager

class DiseaseList(ListView):
  model = Disease
  context_object_name = "disease_list"
  template_name = 'disease_crud/disease_list.html'


class DiseaseUpdate(UserPassesTestMixin, UpdateView):
  model = Disease
  fields = ['name', 'description_ref']
  context_object_name = 'disease'
  template_name = 'disease_crud/disease_update.html'
  
  def get_success_url(self):
    return reverse('therapy:disease_list')

  def test_func(self):
    return MeAccessManager.am_i_employee(self)


class DiseaseCreate(UserPassesTestMixin, CreateView):
  model = Disease
  fields = ['name', 'description_ref']
  template_name = 'disease_crud/disease_create.html'

  def get_success_url(self):
    return reverse('therapy:disease_list')

  def test_func(self):
    return MeAccessManager.am_i_employee(self)


class DiseaseDelete(UserPassesTestMixin, DeleteView):
  model = Disease
  context_object_name = 'disease'
  template_name = 'disease_crud/disease_delete.html'

  def get_success_url(self):
    return reverse('therapy:disease_list')

  def test_func(self):
    return MeAccessManager.am_i_employee(self)



class SymptomList(ListView):
  model = Symptom
  context_object_name = "symptom_list"
  template_name = 'symptom_crud/symptom_list.html'


class SymptomUpdate(UserPassesTestMixin, UpdateView):
  model = Symptom
  fields = ['name', 'description_ref']
  context_object_name = 'symptom'
  template_name = 'symptom_crud/symptom_update.html'
  
  def get_success_url(self):
    return reverse('therapy:symptom_list')

  def test_func(self):
    return MeAccessManager.am_i_employee(self)


class SymptomCreate(UserPassesTestMixin, CreateView):
  model = Symptom
  fields = ['name', 'description_ref']
  template_name = 'symptom_crud/symptom_create.html'

  def get_success_url(self):
    return reverse('therapy:symptom_list')

  def test_func(self):
    return MeAccessManager.am_i_employee(self)


class SymptomDelete(UserPassesTestMixin, DeleteView):
  model = Symptom
  context_object_name = 'symptom'
  template_name = 'symptom_crud/symptom_delete.html'

  def get_success_url(self):
    return reverse('therapy:symptom_list')

  def test_func(self):
    return MeAccessManager.am_i_employee(self)

sanatorium/therapy/templates/symptom_crud/symptom_create.html
{% extends "base_and_header_bar.html" %}

{% block title %}
New Symptom
{% endblock %}

{% block maintext %}
New Symptom
{% endblock %}

{% block content_after_header_bar %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}

sanatorium/therapy/templates/symptom_crud/symptom_delete.html
{% extends "base_and_header_bar.html" %}

{% block title %}
Delete {{ symptom.name }}
{% endblock %}

{% block maintext %}
Delete {{ symptom.name }}
{% endblock %}

{% block content_after_header_bar %}

<form method="post">
  {% csrf_token %}
  <p>Delete {{ symptom }}?</p>
  <button type="submit">Delete</button>
</form>

{% endblock %}

sanatorium/therapy/templates/symptom_crud/symptom_list.html
{% extends "base_and_header_bar.html" %}

{% block title %}
Symptoms
{% endblock %}

{% block maintext %}
Symptoms
{% endblock %}

{% block content_after_header_bar %}

<table>
  <tr class="first-table-row">
    <th>№</th>
    <th>Name</th>
    <th>Description</th>
    {% if user.employee %}
      <th></th>
      <th></th>
    {% endif %}
  </tr>

  {% for symptom in symptom_list %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ symptom.name }}</td>
      <td>
        {% if symptom.description_ref is not None %}
          <a href="{{ symptom.description_ref }}">
            {{ symptom.description_ref }}
          </a>
        {% endif %}
      </td>
      {% if user.employee %}
        <td>
          <a href="{% url 'therapy:symptom_update' symptom.id %}">Edit</a>
        </td>
        <td>
          <a href="{% url 'therapy:symptom_delete' symptom.id %}">Delete</a>
        </td>
      {% endif %}
    </tr>
  {% endfor %}
</table>
{% if user.employee %}
  <form style="margin-top: 20px;" action="{% url 'therapy:symptom_create' %}">
    <button type="submit">Add Symptom</button>
  </form>
{% endif %}

{% endblock %}

sanatorium/therapy/templates/symptom_crud/symptom_update.html
{% extends "base_and_header_bar.html" %}

{% block title %}
{{ symptom.name }}
{% endblock %}

{% block maintext %}
Edit {{ symptom.name }}
{% endblock %}

{% block content_after_header_bar %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}