sanatorium/cooperation/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import HospitalList, HospitalCreate, HospitalUpdate, HospitalDelete

app_name = 'cooperation'

urlpatterns = [
  path('hospital_list/', login_required(HospitalList.as_view()), name='hospital_list'),
  path('hospital_create/', login_required(HospitalCreate.as_view()), name='hospital_create'),
  path('hospital/<int:pk>/', login_required(HospitalUpdate.as_view()), name='hospital_update'),
  path('hospital_delete/<int:pk>/', login_required(HospitalDelete.as_view()), name='hospital_delete'),

  
]

sanatorium/sanatorium/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import main

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('users.urls', namespace='accounts'), name='accounts'),
    path('users/', include('users.urls', namespace='users'), name='users'),
    path('therapy/', include('therapy.urls', namespace='therapy'), name='therapy'),
    path('cooperation/', include('cooperation.urls', namespace='cooperation'), name='cooperation'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),

    path('', login_required(main), name=''),
    path('main/', login_required(main), name='main')
]

sanatorium/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import myprofile, signup, myprofile_edit, profile, \
                    EmployeeList, EmployeeCreate, EmployeeUpdate, EmployeeDelete, \
                    PatientList, PatientCreate, PatientUpdate, PatientDelete, \
                    UserList, UserUpdate

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='/main'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/users/login'), name='logout'),
    path('myprofile/',  login_required(myprofile), name='myprofile'),
    path('profile/<int:pk>',  login_required(profile), name='profile'),
    path('myprofile_edit', login_required(myprofile_edit), name='myprofile_edit'),
    path('signup/', signup, name='signup'),

    path('employee_list/', login_required(EmployeeList.as_view()), name='employee_list'),
    path('employee_create/', login_required(EmployeeCreate.as_view()), name='employee_create'),
    path('employee/<int:pk>/', login_required(EmployeeUpdate.as_view()), name='employee_update'),
    path('employee_delete/<int:pk>/', login_required(EmployeeDelete.as_view()), name='employee_delete'),
    
    path('patient_list/', login_required(PatientList.as_view()), name='patient_list'),
    path('patient_create/', login_required(PatientCreate.as_view()), name='patient_create'),
    path('patient/<int:pk>/', login_required(PatientUpdate.as_view()), name='patient_update'),
    path('patient_delete/<int:pk>/', login_required(PatientDelete.as_view()), name='patient_delete'),

    path('user_list/', login_required(UserList.as_view()), name='user_list'),
    path('user/<int:pk>/', login_required(UserUpdate.as_view()), name='user_update'),
]

sanatorium/cooperation/models.py
from re import I
from tkinter.tix import Tree
from django.db import models
from payments.models import Bill
from meclasses.MeSignalManager import *

hospital_default_change = 20


class Hospital(models.Model):
  name = models.CharField(max_length=254)
  bill = models.OneToOneField(Bill, on_delete=models.PROTECT, blank=True)
  
  def __str__(self):
    return f"{self.name}"

  def save(self, *args, **kwargs):
    if not hasattr(self, 'bill'):
      bill = Bill()
      bill.info = f"hospital {self}"
      bill.change = hospital_default_change
      bill.save()
      self.bill = bill
    super(Hospital, self).save(*args, **kwargs)

delete_hospital_signal(Hospital)

sanatorium/users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from payments.models import Bill
from meclasses.MeSignalManager import *

from therapy.models import Disease, Symptom
from cooperation.models import Hospital

patient_default_change = 30
employee_default_change = 50


class UserManager(BaseUserManager):

  def _create_user(self, first_name, second_name, email, password, is_staff, is_superuser, **extra_fields):
    if not email:
        raise ValueError('Users must have an email address')
    now = timezone.now()
    email = self.normalize_email(email)
    user = self.model(
        first_name=first_name,
        second_name=second_name,
        email=email,
        is_staff=is_staff,
        is_active=True,
        is_superuser=is_superuser,
        last_login=now,
        date_joined=now, 
        **extra_fields
    )
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_user(self, first_name, second_name, email, password, **extra_fields):
    return self._create_user(first_name, second_name, email, password, False, False, **extra_fields)

  def create_superuser(self, first_name, second_name, email, password, **extra_fields):
    user=self._create_user(first_name, second_name, email, password, True, True, **extra_fields)
    return user


class User(AbstractBaseUser, PermissionsMixin):
  first_name = models.CharField(max_length=254)
  second_name = models.CharField(max_length=254)
  email = models.EmailField(max_length=254, unique=True)
  hospitals = models.ManyToManyField(Hospital, blank=True)
  is_staff = models.BooleanField(default=False)
  is_superuser = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)
  last_login = models.DateTimeField(null=True, blank=True)
  date_joined = models.DateTimeField(auto_now_add=True)
  

  USERNAME_FIELD = 'email'
  EMAIL_FIELD = 'email'
  REQUIRED_FIELDS = ['first_name', 'second_name']

  objects = UserManager()

  def __str__(self):
    return f"{self.first_name} {self.second_name}"

  def get_absolute_url(self):
      return "/users/%i/" % (self.pk)


class Employee(models.Model):
  user = models.OneToOneField(User, on_delete=models.PROTECT, primary_key=True)
  speciality = models.CharField(max_length=20)
  bill = models.OneToOneField(Bill, on_delete=models.PROTECT, blank=True)

  def __str__(self):
    return f"{self.speciality} {self.user.first_name} {self.user.second_name}"

  def save(self, *args, **kwargs):
    if not hasattr(self, 'bill'):
      bill = Bill()
      bill.info = f"employee {self}"
      bill.change = employee_default_change
      bill.save()
      self.bill = bill
    super(Employee, self).save(*args, **kwargs)

delete_employee_signal(Employee)


class Patient(models.Model):
  user = models.OneToOneField(User, on_delete=models.PROTECT, primary_key=True)
  diseases = models.ManyToManyField(Disease, blank=True)
  symptoms = models.ManyToManyField(Symptom, blank=True)
  hospital = models.ForeignKey(Hospital, on_delete=models.PROTECT, null=True, blank=True)
  bill = models.OneToOneField(Bill, on_delete=models.PROTECT, null=True, blank=True)

  def save(self, *args, **kwargs):
    if self.hospital == None:
      bill = Bill()
      bill.info = f"patient {self}"
      bill.change = patient_default_change
      bill.save()
      self.bill = bill
    super(Patient, self).save(*args, **kwargs)

  def __str__(self):
    return f"{self.user.first_name} {self.user.second_name}"

delete_patient_signal(Patient)

sanatorium/cooperation/views.py
import imp
from tkinter.messagebox import NO
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from multiprocessing import context, get_context
from django.shortcuts import render, redirect
from .models import Hospital
from payments.models import Bill
from meclasses.MeAccessManager import MeAccessManager


class HospitalList(ListView):
  model = Hospital
  context_object_name = "hospital_list"
  template_name = 'hospital_crud/hospital_list.html'


class HospitalUpdate(UserPassesTestMixin, UpdateView):
  model = Hospital
  fields = ['name']
  context_object_name = 'hospital'
  template_name = 'hospital_crud/hospital_update.html'
  
  def get_success_url(self):
    return reverse('cooperation:hospital_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)


class HospitalCreate(UserPassesTestMixin, CreateView):
  model = Hospital
  fields = ['name']
  template_name = 'hospital_crud/hospital_create.html'

  def get_success_url(self):
    return reverse('cooperation:hospital_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)


class HospitalDelete(UserPassesTestMixin, DeleteView):
  model = Hospital
  context_object_name = 'hospital'
  template_name = 'hospital_crud/hospital_delete.html'

  def get_success_url(self):
    return reverse('cooperation:hospital_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)

sanatorium/cooperation/templates/hospital_crud/hospital_create.html
{% extends "base_and_header_bar.html" %}

{% block title %}
New Hospital
{% endblock %}

{% block maintext %}
New Hospital
{% endblock %}

{% block content_after_header_bar %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}

sanatorium/cooperation/templates/hospital_crud/hospital_delete.html
{% extends "base_and_header_bar.html" %}

{% block title %}
Delete {{ hospital.name }}
{% endblock %}

{% block maintext %}
Delete {{ hospital.name }}
{% endblock %}

{% block content_after_header_bar %}

<form method="post">
  {% csrf_token %}
  <p>Delete {{ hospital }}?</p>
  <button type="submit">Delete</button>
</form>

{% endblock %}

sanatorium/cooperation/templates/hospital_crud/hospital_list.html
{% extends "base_and_header_bar.html" %}

{% block title %}
Hospitals
{% endblock %}

{% block maintext %}
Hospitals
{% endblock %}

{% block content_after_header_bar %}

<table>
  <tr class="first-table-row">
    <th>№</th>
    <th>Name</th>
    {% if user.employee %}
      <th>Patients</th>
    {% endif %}
    {% if user.employee.speciality == "manager" %}
      <th></th>
      <th></th>
    {% endif %}
  </tr>

  {% for hospital in hospital_list %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ hospital.name }}</td>
      {% if user.employee %}
      <td>
        {% for patient in hospital.patient_set.all %}
          {{ patient|linebreaks }}
        {% endfor %}
      </td>
      {% endif %}
      {% if user.employee.speciality == "manager" %}
        <td>
          <a href="{% url 'cooperation:hospital_update' hospital.id %}">Edit</a>
        </td>
        <td>
          <a href="{% url 'cooperation:hospital_delete' hospital.id %}">Delete</a>
        </td>
      {% endif %}
    </tr>
  {% endfor %}
</table>
{% if user.employee.speciality == "manager" %}
  <form style="margin-top: 20px;" action="{% url 'cooperation:hospital_create' %}">
    <button type="submit">Add Hospital</button>
  </form>
{% endif %}

{% endblock %}

sanatorium/cooperation/templates/hospital_crud/hospital_update.html
{% extends "base_and_header_bar.html" %}

{% block title %}
{{ hospital.name }}
{% endblock %}

{% block maintext %}
Edit {{ hospital.name }}
{% endblock %}

{% block content_after_header_bar %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}