sanatorium/payments/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import BillList, BillUpdate, PaymentList, pay_bill, pay_hospital_bill, get_wages

app_name = 'payments'

urlpatterns = [
  path('bill_list/', login_required(BillList.as_view()), name='bill_list'),
  path('bill/<int:pk>/', login_required(BillUpdate.as_view()), name='bill_update'),

  path('payment_list/', login_required(PaymentList.as_view()), name='payment_list'),

  path('pay_bill/<int:pk>/', login_required(pay_bill), name='pay_bill'),
  path('pay_hospital_bill/<int:pk>/', login_required(pay_hospital_bill), name='pay_hospital_bill'),
  path('get_wages/<int:pk>/', login_required(get_wages), name='get_wages'),
]

sanatorium/sanatorium/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import main

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('users.urls', namespace='accounts'), name='accounts'),
    path('users/', include('users.urls', namespace='users'), name='users'),
    path('therapy/', include('therapy.urls', namespace='therapy'), name='therapy'),
    path('cooperation/', include('cooperation.urls', namespace='cooperation'), name='cooperation'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),

    path('', login_required(main), name=''),
    path('main/', login_required(main), name='main')
]

sanatorium/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import myprofile, signup, myprofile_edit, profile, \
                    EmployeeList, EmployeeCreate, EmployeeUpdate, EmployeeDelete, \
                    PatientList, PatientCreate, PatientUpdate, PatientDelete, \
                    UserList, UserUpdate

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='/main'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/users/login'), name='logout'),
    path('myprofile/',  login_required(myprofile), name='myprofile'),
    path('profile/<int:pk>',  login_required(profile), name='profile'),
    path('myprofile_edit', login_required(myprofile_edit), name='myprofile_edit'),
    path('signup/', signup, name='signup'),

    path('employee_list/', login_required(EmployeeList.as_view()), name='employee_list'),
    path('employee_create/', login_required(EmployeeCreate.as_view()), name='employee_create'),
    path('employee/<int:pk>/', login_required(EmployeeUpdate.as_view()), name='employee_update'),
    path('employee_delete/<int:pk>/', login_required(EmployeeDelete.as_view()), name='employee_delete'),
    
    path('patient_list/', login_required(PatientList.as_view()), name='patient_list'),
    path('patient_create/', login_required(PatientCreate.as_view()), name='patient_create'),
    path('patient/<int:pk>/', login_required(PatientUpdate.as_view()), name='patient_update'),
    path('patient_delete/<int:pk>/', login_required(PatientDelete.as_view()), name='patient_delete'),

    path('user_list/', login_required(UserList.as_view()), name='user_list'),
    path('user/<int:pk>/', login_required(UserUpdate.as_view()), name='user_update'),
]

sanatorium/users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from payments.models import Bill
from meclasses.MeSignalManager import *

from therapy.models import Disease, Symptom
from cooperation.models import Hospital

patient_default_change = 30
employee_default_change = 50


class UserManager(BaseUserManager):

  def _create_user(self, first_name, second_name, email, password, is_staff, is_superuser, **extra_fields):
    if not email:
        raise ValueError('Users must have an email address')
    now = timezone.now()
    email = self.normalize_email(email)
    user = self.model(
        first_name=first_name,
        second_name=second_name,
        email=email,
        is_staff=is_staff,
        is_active=True,
        is_superuser=is_superuser,
        last_login=now,
        date_joined=now, 
        **extra_fields
    )
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_user(self, first_name, second_name, email, password, **extra_fields):
    return self._create_user(first_name, second_name, email, password, False, False, **extra_fields)

  def create_superuser(self, first_name, second_name, email, password, **extra_fields):
    user=self._create_user(first_name, second_name, email, password, True, True, **extra_fields)
    return user


class User(AbstractBaseUser, PermissionsMixin):
  first_name = models.CharField(max_length=254)
  second_name = models.CharField(max_length=254)
  email = models.EmailField(max_length=254, unique=True)
  hospitals = models.ManyToManyField(Hospital, blank=True)
  is_staff = models.BooleanField(default=False)
  is_superuser = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)
  last_login = models.DateTimeField(null=True, blank=True)
  date_joined = models.DateTimeField(auto_now_add=True)
  

  USERNAME_FIELD = 'email'
  EMAIL_FIELD = 'email'
  REQUIRED_FIELDS = ['first_name', 'second_name']

  objects = UserManager()

  def __str__(self):
    return f"{self.first_name} {self.second_name}"

  def get_absolute_url(self):
      return "/users/%i/" % (self.pk)


class Employee(models.Model):
  user = models.OneToOneField(User, on_delete=models.PROTECT, primary_key=True)
  speciality = models.CharField(max_length=20)
  bill = models.OneToOneField(Bill, on_delete=models.PROTECT, blank=True)

  def __str__(self):
    return f"{self.speciality} {self.user.first_name} {self.user.second_name}"

  def save(self, *args, **kwargs):
    if not hasattr(self, 'bill'):
      bill = Bill()
      bill.info = f"employee {self}"
      bill.change = employee_default_change
      bill.save()
      self.bill = bill
    super(Employee, self).save(*args, **kwargs)

delete_employee_signal(Employee)


class Patient(models.Model):
  user = models.OneToOneField(User, on_delete=models.PROTECT, primary_key=True)
  diseases = models.ManyToManyField(Disease, blank=True)
  symptoms = models.ManyToManyField(Symptom, blank=True)
  hospital = models.ForeignKey(Hospital, on_delete=models.PROTECT, null=True, blank=True)
  bill = models.OneToOneField(Bill, on_delete=models.PROTECT, null=True, blank=True)

  def save(self, *args, **kwargs):
    if self.hospital == None:
      bill = Bill()
      bill.info = f"patient {self}"
      bill.change = patient_default_change
      bill.save()
      self.bill = bill
    super(Patient, self).save(*args, **kwargs)

  def __str__(self):
    return f"{self.user.first_name} {self.user.second_name}"

delete_patient_signal(Patient)

sanatorium/users/forms.py
from tkinter.tix import Tree
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.password_validation import validate_password
from .models import User

 
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    second_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'second_name', 'email',)

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.second_name = self.cleaned_data["second_name"]
        if commit:
            user.save()
        return user


class ProfileEditForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    second_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'second_name', 'email', 'password')

    def save(self, commit=True):
        user = super(ProfileEditForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.second_name = self.cleaned_data["second_name"]
        user.set_password(self.clean_password())
        if commit:
            user.save()
        return user

    def clean_password(self):
        password = self.cleaned_data.get('password')
        try:
            validate_password(password, self.instance)
        except forms.ValidationError as error:
            self.add_error('password', error)
        return password

sanatorium/users/views.py
from multiprocessing import context
from tkinter import N
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.urls import reverse
from meclasses.MeAccessManager import MeAccessManager
from users.models import Patient, Employee, User
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from payments.models import Bill

from .forms import SignUpForm, ProfileEditForm


def myprofile(request):
  context = {'user': request.user}
  return render(request, template_name='myprofile.html', context=context)
  

def signup(request):
  if request.method == 'POST':
      form = SignUpForm(request.POST)
      if form.is_valid():
          user = form.save()
          raw_password = form.cleaned_data.get('password1')
          user = authenticate(request, email=user.email, password=raw_password)
          if user is not None:
              login(request, user)
          else:
              print("user is not authenticated")
          return redirect('users:myprofile')
  else:
      form = SignUpForm()
  return render(request, 'signup.html', {'form': form})


def myprofile_edit(request):
  if request.method == 'POST':
    form = ProfileEditForm(request.POST, instance=request.user)
    form.actual_user = request.user
    if form.is_valid():
      user = form.save()
      user = authenticate(request, email=user.email, password=form.cleaned_data["password"])
      if user is not None:
        login(request, user)
      else:
        print("user is not authenticated")
      return redirect('users:myprofile')
  else:
    form = ProfileEditForm(initial={
      "first_name": request.user.first_name,
      "second_name": request.user.second_name,
      "email": request.user.email})
  return render(request, 'myprofileedit.html', {'form': form})


def profile(request, pk):
  if pk == request.user.id:
    return redirect(reverse('users:myprofile'))
  context = {'user': request.user}
  try:
    user = User.objects.get(id=pk)
    context['profile'] = user
    return render(request, template_name='profile.html', context=context)
  except User.DoesNotExist:
    return HttpResponseNotFound('<h1>404 Page not found</h1>')



class EmployeeList(UserPassesTestMixin, ListView):
  model = Employee
  context_object_name = "employee_list"
  template_name = 'employee_crud/employee_list.html'
  
  def test_func(self):
    return MeAccessManager.am_i_manager(self)


class EmployeeUpdate(UserPassesTestMixin, UpdateView):
  model = Employee
  fields = ['speciality']
  context_object_name = 'employee'
  template_name = 'employee_crud/employee_update.html'
  
  def get_success_url(self):
    return reverse('users:employee_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)


class EmployeeCreate(UserPassesTestMixin, CreateView):
  model = Employee
  fields = ['user', 'speciality']
  template_name = 'employee_crud/employee_create.html'

  def get_success_url(self):
    return reverse('users:employee_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)


class EmployeeDelete(UserPassesTestMixin, DeleteView):
  model = Employee
  context_object_name = 'employee'
  template_name = 'employee_crud/employee_delete.html'

  def get_success_url(self):
    return reverse('users:employee_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)



class PatientList(UserPassesTestMixin, ListView):
  model = Patient
  context_object_name = "patient_list"
  template_name = 'patient_crud/patient_list.html'
  
  def test_func(self):
    return MeAccessManager.am_i_employee(self)


class PatientUpdate(UserPassesTestMixin, UpdateView):
  model = Patient
  fields = ['diseases', 'symptoms']
  context_object_name = 'patient'
  template_name = 'patient_crud/patient_update.html'
  
  def get_success_url(self):
    return reverse('users:patient_list')

  def test_func(self):
    return MeAccessManager.am_i_employee(self)


class PatientCreate(UserPassesTestMixin, CreateView):
  model = Patient
  fields = ['user', 'diseases', 'symptoms', 'hospital']
  template_name = 'patient_crud/patient_create.html'

  def get_success_url(self):
    return reverse('users:patient_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)


class PatientDelete(UserPassesTestMixin, DeleteView):
  model = Patient
  context_object_name = 'patient'
  template_name = 'patient_crud/patient_delete.html'

  def get_success_url(self):
    return reverse('users:patient_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)



class UserList(ListView):
  model = User
  context_object_name = "user_list"
  template_name = 'user_crud/user_list.html'

class UserUpdate(UserPassesTestMixin, UpdateView):
  model = User
  fields = ['hospitals']
  context_object_name = 'user_to_update'
  template_name = 'user_crud/user_update.html'
  
  def get_success_url(self):
    return reverse('users:user_list')

  def test_func(self):
    return MeAccessManager.am_i_manager(self)

sanatorium/users/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}

<h1>Log In</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button style="margin-bottom: 10px;" type="submit">Log in</button>
</form>
<a href="{% url 'users:signup' %}">Create an account</a>
{% endblock %}

sanatorium/users/templates/myprofile.html
{% extends "base_and_header_bar.html" %}

{% block title %}
Profile
{% endblock %}

{% block maintext %}
My Profile
{% endblock %}

{% block content_after_header_bar %}

{{ user.first_name }} {{ user.second_name }} <br>
{{ user.email }} <br>
{% if user.employee %}
  {{ user.employee.speciality }} <br>
{% endif %}
{% if user.patient %}
  patient
{% endif %}
{% if user.patient.hospital %}
  from {{ user.patient.hospital }} <br>
{% endif %}

<form action="{% url 'users:myprofile_edit' %}">
  <button style="margin-bottom: 15px; margin-top: 15px;" type="submit">Edit Profile</button>
</form>
<hr>

{% if user.patient.bill_id %}
Your bill: {{ user.patient.bill.amount|floatformat:1 }}
<form action="{% url 'payments:pay_bill' user.patient.bill_id %}">
  <button style="margin-bottom: 15px;" type="submit">Pay My Bill</button>
</form>
{% endif %}

{% for hospital in user.hospitals.all %}
{{ hospital }} bill: {{ hospital.bill.amount|floatformat:1 }}
<form action="{% url 'payments:pay_hospital_bill' hospital.bill_id %}">
  <button style="margin-bottom: 15px;" type="submit">Pay Hospital Bill</button>
</form>
{% endfor %}


{% if user.employee %}
Your wages: {{ user.employee.bill.amount|floatformat:1 }}
<form action="{% url 'payments:get_wages' user.employee.bill_id %}">
  <button style="margin-bottom: 15px;" type="submit">Get Wages</button>
</form>
{% endif %}

{% endblock %}

sanatorium/users/templates/myprofileedit.html
{% extends "base_and_header_bar.html" %}

{% block title %}
Edit Profile
{% endblock %}

{% block maintext %}
Edit Profile
{% endblock %}

{% block content_after_header_bar %}

<form method="post">
  {% csrf_token %}
  {% for field in form %}
    {{ field.label_tag }}
    {{ field }}
    {% for error in field.errors %}
      <p>{{ error }}</p>
    {% endfor %}
  {% endfor %}
  <button style="margin-bottom: 10px; margin-top: 10px; display: block;" type="submit">Save</button>
</form>
{% endblock %}

sanatorium/users/templates/profile.html
{% extends "base_and_header_bar.html" %}

{% block title %}
{{ profile }}
{% endblock %}

{% block maintext %}
{{ profile }}
{% endblock %}

{% block content_after_header_bar %}

{{ profile.first_name }} {{ profile.second_name }} <br>
{{ profile.email }} <br>
{% if user.employee %}
  {% if profile.employee %}
    {{ profile.employee.speciality }} <br>
  {% endif %}
  {% if profile.patient %}
    patient
    {% if profile.patient.hospital %}
      from {{ profile.patient.hospital }} <br>
    {% endif %}
  {% endif %}
{% endif %}
{% endblock %}

sanatorium/users/templates/profileedit.html
{% extends "base.html" %}

{% block title %}
Edit Profile
{% endblock %}

{% block content %}

{% include "buttons/mainbutton.html" %}
{% include "buttons/profilebutton.html" %}
{% include "buttons/logoutbutton.html" %}

<h1>Edit Profile</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

sanatorium/users/templates/signup.html
{% extends "base.html" %}

{% block title %}
SignUp
{% endblock %}

{% block content %}

<h1>Sign Up</h1>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    {{ field.label_tag }}
    {{ field }}
    {% for error in field.errors %}
      <p>{{ error }}</p>
    {% endfor %}
  {% endfor %}
  <button style="margin-bottom: 10px; margin-top: 10px; display: block;" type="submit">Sign up</button>
</form>
<a href="{% url 'users:login' %}">Log In</a>
{% endblock %}