sanatorium/cooperation/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import HospitalList, HospitalCreate, HospitalUpdate, HospitalDelete

app_name = 'cooperation'

urlpatterns = [
  path('hospital_list/', login_required(HospitalList.as_view()), name='hospital_list'),
  path('hospital_create/', login_required(HospitalCreate.as_view()), name='hospital_create'),
  path('hospital/<int:pk>/', login_required(HospitalUpdate.as_view()), name='hospital_update'),
  path('hospital_delete/<int:pk>/', login_required(HospitalDelete.as_view()), name='hospital_delete'),

  
]

sanatorium/payments/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import BillList, BillUpdate, PaymentList, pay_bill, pay_hospital_bill, get_wages

app_name = 'payments'

urlpatterns = [
  path('bill_list/', login_required(BillList.as_view()), name='bill_list'),
  path('bill/<int:pk>/', login_required(BillUpdate.as_view()), name='bill_update'),

  path('payment_list/', login_required(PaymentList.as_view()), name='payment_list'),

  path('pay_bill/<int:pk>/', login_required(pay_bill), name='pay_bill'),
  path('pay_hospital_bill/<int:pk>/', login_required(pay_hospital_bill), name='pay_hospital_bill'),
  path('get_wages/<int:pk>/', login_required(get_wages), name='get_wages'),
]

sanatorium/sanatorium/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import main

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('users.urls', namespace='accounts'), name='accounts'),
    path('users/', include('users.urls', namespace='users'), name='users'),
    path('therapy/', include('therapy.urls', namespace='therapy'), name='therapy'),
    path('cooperation/', include('cooperation.urls', namespace='cooperation'), name='cooperation'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),

    path('', login_required(main), name=''),
    path('main/', login_required(main), name='main')
]

sanatorium/therapy/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import DiseaseDelete, DiseaseList, DiseaseUpdate, DiseaseCreate, \
                    SymptomDelete, SymptomList, SymptomUpdate, SymptomCreate

app_name = 'therapy'

urlpatterns = [
  path('disease_list/', login_required(DiseaseList.as_view()), name='disease_list'),
  path('disease_create/', login_required(DiseaseCreate.as_view()), name='disease_create'),
  path('disease/<int:pk>/', login_required(DiseaseUpdate.as_view()), name='disease_update'),
  path('disease_delete/<int:pk>/', login_required(DiseaseDelete.as_view()), name='disease_delete'),

  path('symtom_list/', login_required(SymptomList.as_view()), name='symptom_list'),
  path('symtom_create/', login_required(SymptomCreate.as_view()), name='symptom_create'),
  path('symtom/<int:pk>/', login_required(SymptomUpdate.as_view()), name='symptom_update'),
  path('symtom_delete/<int:pk>/', login_required(SymptomDelete.as_view()), name='symptom_delete')
]

sanatorium/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import myprofile, signup, myprofile_edit, profile, \
                    EmployeeList, EmployeeCreate, EmployeeUpdate, EmployeeDelete, \
                    PatientList, PatientCreate, PatientUpdate, PatientDelete, \
                    UserList, UserUpdate

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='/main'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/users/login'), name='logout'),
    path('myprofile/',  login_required(myprofile), name='myprofile'),
    path('profile/<int:pk>',  login_required(profile), name='profile'),
    path('myprofile_edit', login_required(myprofile_edit), name='myprofile_edit'),
    path('signup/', signup, name='signup'),

    path('employee_list/', login_required(EmployeeList.as_view()), name='employee_list'),
    path('employee_create/', login_required(EmployeeCreate.as_view()), name='employee_create'),
    path('employee/<int:pk>/', login_required(EmployeeUpdate.as_view()), name='employee_update'),
    path('employee_delete/<int:pk>/', login_required(EmployeeDelete.as_view()), name='employee_delete'),
    
    path('patient_list/', login_required(PatientList.as_view()), name='patient_list'),
    path('patient_create/', login_required(PatientCreate.as_view()), name='patient_create'),
    path('patient/<int:pk>/', login_required(PatientUpdate.as_view()), name='patient_update'),
    path('patient_delete/<int:pk>/', login_required(PatientDelete.as_view()), name='patient_delete'),

    path('user_list/', login_required(UserList.as_view()), name='user_list'),
    path('user/<int:pk>/', login_required(UserUpdate.as_view()), name='user_update'),
]

sanatorium/sanatorium/views.py
from django.shortcuts import render, redirect


def main(request):
  context = {'user': request.user}
  return render(request, template_name='main.html', context=context)

sanatorium/sanatorium/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} - Sanatorium</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    </head>
    <body>
      <div class="container">
        {% block content %}
        
        {% endblock %} 
    </div>
  </body>
</html>

sanatorium/sanatorium/templates/base_and_header_bar.html
{% extends "base.html" %}

{% block content %}
<style>
  .container {
    padding: 0px;
  }
</style>

<div class="header-bar">
  <div>
    <a href="{% url 'main' %}">Main<br></a>
    <a href="{% url 'users:myprofile' %}">My Profile<br></a>
    <a href="{% url 'users:logout' %}">Logout</a>
  </div>
  <div style="margin-left: 30px">
    <h1>{% block maintext %}{% endblock %}</h1>
  </div>
</div>

<div class="content">
{% block content_after_header_bar %}

{% endblock %}
</div>
{% endblock %}

sanatorium/sanatorium/templates/main.html
{% extends "base_and_header_bar.html" %}

{% block title %}
Main
{% endblock %}

{% block maintext %}
Main
{% endblock %}

{% block content_after_header_bar %}

<a style="font-size: larger;" href="{% url 'users:user_list' %}">Users</a>
<br>
<a style="font-size: larger;" href="{% url 'therapy:disease_list' %}">Diseases</a>
<br>
<a style="font-size: larger;" href="{% url 'therapy:symptom_list' %}">Symptoms</a>
<br>
<a style="font-size: larger;" href="{% url 'cooperation:hospital_list' %}">Hospitals</a>
<br>
{% if user.employee %}
<a style="font-size: larger;" href="{% url 'users:patient_list' %}">Patients</a>
<br>
{% endif %}
{% if user.employee.speciality == "manager" %}
<a style="font-size: larger;" href="{% url 'users:employee_list' %}">Employees</a>
<br>
{% endif %}
{% if user.employee.speciality == "manager" %}
<a style="font-size: larger;" href="{% url 'payments:bill_list' %}">Bills</a>
<br>
{% endif %}
{% if user.employee.speciality == "manager" %}
<a style="font-size: larger;" href="{% url 'payments:payment_list' %}">Payments</a>
<br>
{% endif %}

{% endblock %}